server:
  port: 9000
  address: 192.168.0.1
  hostname: localhost
  contextPath: /my-project
  date: 2018-02-21
  time: 11:40:50

environment:
  username: ubuntu
  homeDirectory: /home/ubuntu
  lang: en_US.UTF-8